# inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  Include:
    - 'Gemfile'
    - 'Rakefile'
    - 'ididthis.gemspec'
  Exclude:
    - bin/*
    - vendor/**/*

# Enforce outdented access modifiers
AccessModifierIndentation:
  EnforcedStyle: outdent

EmptyLinesAroundAccessModifier:
  Enabled: true

# Standardize on double quotes
StringLiterals:
  EnforcedStyle: double_quotes
